### ISSUE TITLE
npm install后无法完成npm test了

### ISSUE THREAD

**Issue by try4148** [fibjs/fib-app#43]
使用首页例子代码运行，后台显示错误
/node_modules/fib-app/node_modules/viz.js/viz.js:1627015: Invalid asm.js: Function definition doesn't match use
系统 centos 7 x64
fibjs版本 0.27

**Comment by richardo2016** [comment]
> 使用首页例子代码运行，后台显示错误
> /node_modules/fib-app/node_modules/viz.js/viz.js:1627015: Invalid asm.js: Function definition doesn't match use
> 系统 centos 7 x64
> fibjs版本 0.27

你好，可以给出更详细的情况么？或者发微信到 richardo2016@gmail.com 我拉你进群解答
