### ISSUE TITLE
GraphQL queries will yield an error when corresponding values exceed 2^31-1.

### ISSUE THREAD

**Issue by PinelliaC** [fibjs/fib-app#58]
Even when the database is set to **use the 'bigint' data type**, GraphQL queries will yield an error when corresponding values exceed 2^31-1.

<img width="585" alt="image" src="https://user-images.githubusercontent.com/35207295/232021462-5650d3be-ffec-4c6d-8ac7-2411556cf6e9.png">

see: https://github.com/graphql/graphql-spec/issues/73

**Comment by richardo2016** [comment]
supported since v1.16.9 

https://github.com/fibjs/fib-app/commit/dfb8421f80e5c6f806dfd62cb313cf544c42d60c
